"""empty message

Revision ID: 015a93b152b2
Revises: 5a8be295ea87
Create Date: 2018-02-24 13:25:32.762000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '015a93b152b2'
down_revision = '5a8be295ea87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('blog_type', sa.String(length=10), nullable=True))
    op.add_column('article', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('article', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body', mysql.TEXT(), nullable=True))
    op.drop_column('article', 'content')
    op.drop_column('article', 'blog_type')
    # ### end Alembic commands ###
