"""empty message

Revision ID: 1ac27858950d
Revises: 0a1efebe492e
Create Date: 2018-02-03 17:26:20.321000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac27858950d'
down_revision = '0a1efebe492e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('father_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'father_name')
    # ### end Alembic commands ###
