"""empty message

Revision ID: 2ebf6c03175b
Revises: d9bb289eb489
Create Date: 2018-03-28 19:58:47.441000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ebf6c03175b'
down_revision = 'd9bb289eb489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('article', 'pagedown')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('pagedown', mysql.TEXT(), nullable=True))
    op.drop_column('article', 'content')
    # ### end Alembic commands ###
