"""empty message

Revision ID: 7dadf9c63925
Revises: dbf9c59c34a3
Create Date: 2018-03-12 16:37:47.300000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dadf9c63925'
down_revision = 'dbf9c59c34a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('pagedown', sa.Text(), nullable=True))
    op.drop_column('article', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column('article', 'pagedown')
    op.drop_column('article', 'body_html')
    # ### end Alembic commands ###
