"""empty message

Revision ID: d9bb289eb489
Revises: 7dadf9c63925
Create Date: 2018-03-21 15:57:26.704000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bb289eb489'
down_revision = '7dadf9c63925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('read_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'read_count')
    # ### end Alembic commands ###
