"""empty message

Revision ID: dbf9c59c34a3
Revises: 015a93b152b2
Create Date: 2018-03-01 16:17:08.070000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbf9c59c34a3'
down_revision = '015a93b152b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('tags', sa.String(length=30), nullable=True))
    op.add_column('article', sa.Column('type', sa.String(length=10), nullable=True))
    op.drop_column('article', 'blog_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('blog_type', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('article', 'type')
    op.drop_column('article', 'tags')
    # ### end Alembic commands ###
